<?php
namespace App\Enums;
enum AssignmentStatus: string {
    case PENDING='PENDING'; case ONGOING='ONGOING'; case SUBMITTED_QC='SUBMITTED_QC';
    case QC_REVIEWING='QC_REVIEWING'; case REWORK='REWORK'; case COMPLETED='COMPLETED';
    case DUPLICATE_REVIEW='DUPLICATE_REVIEW'; case DUPLICATE_CONFIRMED='DUPLICATE_CONFIRMED'; case CANCELLED='CANCELLED';
}
