<?php
namespace App\Enums;
enum AuditAction: string {
    case TEAM_CREATED='TEAM_CREATED'; case TEAM_UPDATED='TEAM_UPDATED'; case TEAM_DEACTIVATED='TEAM_DEACTIVATED'; case TEAM_REACTIVATED='TEAM_REACTIVATED';
    case ALLOWED_EMAIL_CREATED='ALLOWED_EMAIL_CREATED'; case ALLOWED_EMAIL_UPDATED='ALLOWED_EMAIL_UPDATED'; case ALLOWED_EMAIL_DISABLED='ALLOWED_EMAIL_DISABLED'; case ALLOWED_EMAIL_ENABLED='ALLOWED_EMAIL_ENABLED';
    case USER_STATUS_CHANGED='USER_STATUS_CHANGED'; case USER_CAPABILITIES_CHANGED='USER_CAPABILITIES_CHANGED'; case QC_SCOPES_CHANGED='QC_SCOPES_CHANGED'; case USER_PERMISSION_OVERRIDE_CHANGED='USER_PERMISSION_OVERRIDE_CHANGED'; case USER_PERMISSION_OVERRIDE_REMOVED='USER_PERMISSION_OVERRIDE_REMOVED';
    case CLIENT_CREATED='CLIENT_CREATED'; case CLIENT_UPDATED='CLIENT_UPDATED'; case CLIENT_DEACTIVATED='CLIENT_DEACTIVATED'; case CLIENT_REACTIVATED='CLIENT_REACTIVATED'; case CLIENT_SHEET_URL_CHANGED='CLIENT_SHEET_URL_CHANGED'; case CLIENT_TIER_CORRECTED='CLIENT_TIER_CORRECTED';
    case CATALOG_CREATED='CATALOG_CREATED'; case CATALOG_UPDATED='CATALOG_UPDATED';
    case WORK_ORDER_CREATED='WORK_ORDER_CREATED'; case ASSIGNMENT_STARTED='ASSIGNMENT_STARTED'; case ASSIGNMENT_PROGRESS_UPDATED='ASSIGNMENT_PROGRESS_UPDATED';
}
