<?php

namespace App\Enums;

enum AuditAction: string
{
    case TEAM_CREATED = 'TEAM_CREATED';
    case TEAM_UPDATED = 'TEAM_UPDATED';
    case TEAM_DEACTIVATED = 'TEAM_DEACTIVATED';
    case TEAM_REACTIVATED = 'TEAM_REACTIVATED';

    case ALLOWED_EMAIL_CREATED = 'ALLOWED_EMAIL_CREATED';
    case ALLOWED_EMAIL_UPDATED = 'ALLOWED_EMAIL_UPDATED';
    case ALLOWED_EMAIL_DISABLED = 'ALLOWED_EMAIL_DISABLED';
    case ALLOWED_EMAIL_ENABLED = 'ALLOWED_EMAIL_ENABLED';

    case USER_STATUS_CHANGED = 'USER_STATUS_CHANGED';
    case USER_CAPABILITIES_CHANGED = 'USER_CAPABILITIES_CHANGED';
    case QC_SCOPES_CHANGED = 'QC_SCOPES_CHANGED';
    case USER_PERMISSION_OVERRIDE_CHANGED = 'USER_PERMISSION_OVERRIDE_CHANGED';
    case USER_PERMISSION_OVERRIDE_REMOVED = 'USER_PERMISSION_OVERRIDE_REMOVED';
}
